# Generated by Django 4.0 on 2023-02-10 08:20

import autohouse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_preferred_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_car',
            field=models.JSONField(null=True, validators=[autohouse.validators.CharacteristicJSONValidationSchema(limit_value={'$schema': 'http://json-schema.org/draft-04/schema#', 'properties': {'body_type': {'enum': ['sedan', 'coupe', 'hatchback', 'minivan', 'pickup']}, 'brand': {'type': 'string'}, 'color': {'items': {'type': 'string'}, 'type': 'array', 'uniqueItems': True}, 'horse_power': {'properties': {'actions': {'default': 'in', 'enum': ['gt', 'gte', 'lt', 'lte', 'eq']}, 'value': {'minimum': 1, 'type': 'integer'}}, 'required': ['value', 'actions'], 'type': 'object'}, 'model': {'type': 'string'}, 'transmission_type': {'enum': ['manual', 'automatic', 'cvt']}, 'year_of_issue': {'properties': {'actions': {'enum': ['gt', 'gte', 'lt', 'lte', 'eq']}, 'value': {'minimum': 1800, 'type': 'integer'}}, 'required': ['value', 'actions'], 'type': 'object'}}, 'type': 'object'})]),
        ),
    ]
