# Generated by Django 4.0 on 2023-02-15 10:19

import autohouse.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_preferred_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_car',
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('preferred_car', models.JSONField(null=True, validators=[autohouse.validators.CharacteristicJSONValidationSchema(limit_value={'$schema': 'http://json-schema.org/draft-04/schema#', 'properties': {'body_type': {'enum': ['sedan', 'coupe', 'hatchback', 'minivan', 'pickup']}, 'brand': {'type': 'string'}, 'color': {'items': {'type': 'string'}, 'type': 'array', 'uniqueItems': True}, 'horse_power': {'properties': {'actions': {'default': 'in', 'enum': ['gt', 'gte', 'lt', 'lte', 'eq']}, 'value': {'minimum': 1, 'type': 'integer'}}, 'required': ['value', 'actions'], 'type': 'object'}, 'model': {'type': 'string'}, 'transmission_type': {'enum': ['manual', 'automatic', 'cvt']}, 'year_of_issue': {'properties': {'actions': {'enum': ['gt', 'gte', 'lt', 'lte', 'eq']}, 'value': {'minimum': 1800, 'type': 'integer'}}, 'required': ['value', 'actions'], 'type': 'object'}}, 'type': 'object'})])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1.0)])),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
