# Generated by Django 4.0 on 2023-02-16 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohouse', '0009_alter_autohouse_prefer_characteristic'),
        ('main', '0003_remove_car_price'),
        ('customer', '0005_remove_customer_preferred_car_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1.0)])),
                ('autohouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autohouse.autohouse')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
