# Generated by Django 4.0 on 2023-02-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_car_price'),
        ('customer', '0006_customercar'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
