# Generated by Django 4.0 on 2023-02-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_offer_car_offer_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCar',
        ),
    ]
