# Generated by Django 4.0 on 2023-01-10 20:28

import autohouse.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(validators=[autohouse.validators.CharacteristicJSONValidationSchema(limit_value={'$schema': 'http://json-schema.org/draft-04/schema#', 'properties': {'brand': {'type': 'string'}, 'color': {'type': 'string'}, 'type_of_transmission': {'type': 'string'}, 'year_of_issue': {'format': 'date', 'type': 'string'}}, 'type': 'object'})])),
            ],
        ),
        migrations.CreateModel(
            name='Autohouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('prefer_characteristic', models.ManyToManyField(to='autohouse.Characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autohouse.characteristic')),
            ],
        ),
    ]
