# Generated by Django 4.0 on 2023-01-27 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('supplier', '0002_alter_supplierdiscount_end_date'),
        ('autohouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutohouseDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=main.utils.Util.default_end_date)),
                ('autohouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autohouse.autohouse')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutohouseCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1.0)])),
                ('autohouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autohouse.autohouse')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
