# Generated by Django 4.0 on 2023-01-30 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_year_of_issue'),
        ('supplier', '0002_alter_supplierdiscount_end_date'),
        ('autohouse', '0002_autohousediscount_autohousecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohousecar',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AutoHouseSupplierPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1.0)])),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('autohouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autohouse.autohouse')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
