# Generated by Django 4.0 on 2023-01-12 15:40

import autohouse.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohouse', '0002_car_autohouse_created_at_autohouse_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='horse_power',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year_of_issue',
            field=models.PositiveSmallIntegerField(default=2000, help_text='Use <YYYY> as date format', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='autohouse',
            name='prefer_characteristic',
        ),
        migrations.AddField(
            model_name='autohouse',
            name='prefer_characteristic',
            field=models.JSONField(null=True, validators=[autohouse.validators.CharacteristicJSONValidationSchema(limit_value={'$schema': 'http://json-schema.org/draft-04/schema#', 'properties': {'body-type': {'type': 'string'}, 'brand': {'type': 'string'}, 'color': {'type': 'string'}, 'horse_power': {'minimum': 1, 'type': 'integer'}, 'price': {'type': 'number'}, 'transmission_type': {'type': 'string'}, 'year_of_issue': {'minimum': 1800, 'type': 'integer'}}, 'type': 'object'})]),
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
