# Generated by Django 4.0 on 2023-02-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autohouse', '0003_autohousecar_amount_autohousesupplierpurchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autohousediscount',
            name='autohouse',
        ),
        migrations.RemoveField(
            model_name='autohousediscount',
            name='car',
        ),
        migrations.AddField(
            model_name='autohousediscount',
            name='autohouse_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autohouse.autohousecar'),
        ),
    ]
