# Generated by Django 4.0 on 2023-01-12 15:46

import autohouse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohouse', '0003_remove_car_characteristic_car_body_type_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autohouse',
            name='prefer_characteristic',
            field=models.JSONField(null=True, validators=[autohouse.validators.CharacteristicJSONValidationSchema(limit_value={'$schema': 'http://json-schema.org/draft-04/schema#', 'properties': {'body-type': {'type': 'string'}, 'brand': {'type': 'string'}, 'color': {'type': 'string'}, 'horse_power': {'minimum': 1, 'type': 'integer'}, 'model': {'type': 'string'}, 'price': {'type': 'number'}, 'transmission_type': {'type': 'string'}, 'year_of_issue': {'minimum': 1800, 'type': 'integer'}}, 'type': 'object'})]),
        ),
    ]
