# Generated by Django 4.0 on 2023-01-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohouse', '0006_supplier_remove_car_price_autohouse_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliercar',
            name='autohouse',
        ),
    ]
