# Generated by Django 4.0 on 2023-02-07 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohouse', '0006_alter_autohouse_prefer_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohouse',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=0.01)]),
        ),
    ]
