# Generated by Django 4.0 on 2023-01-27 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('horse_power', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('year_of_issue', models.PositiveSmallIntegerField(help_text='Use <YYYY> as date format', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)])),
                ('transmission_type', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic'), ('cvt', 'cvt')], max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
