# Generated by Django 4.0 on 2023-02-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_year_of_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
