# Generated by Django 4.0 on 2023-01-27 14:58

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdiscount',
            name='end_date',
            field=models.DateTimeField(default=main.utils.Util.default_end_date),
        ),
    ]
