# Generated by Django 4.0 on 2023-02-02 10:32

import django.core.validators
from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplierdiscount_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='year_of_foundation',
            field=models.PositiveSmallIntegerField(default=1800, help_text='Use <YYYY> as date format', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(main.utils.Util.current_year)]),
        ),
    ]
