# Generated by Django 4.0 on 2023-02-02 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_year_of_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='number_of_buyers',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
