# Generated by Django 4.0 on 2023-02-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_number_of_buyers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierdiscount',
            name='car',
        ),
        migrations.RemoveField(
            model_name='supplierdiscount',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplierdiscount',
            name='supplier_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.suppliercar'),
        ),
    ]
