# Generated by Django 4.0 on 2023-02-07 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_remove_supplierdiscount_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1.0)]),
        ),
    ]
